// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RecipesAPI.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Register
    {
        /// <summary>
        /// Initializes a new instance of the Register class.
        /// </summary>
        public Register() { }

        /// <summary>
        /// Initializes a new instance of the Register class.
        /// </summary>
        public Register(string name, string surname, string email, string password, string confirmPassword)
        {
            Name = name;
            Surname = surname;
            Email = email;
            Password = password;
            ConfirmPassword = confirmPassword;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "surname")]
        public string Surname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "confirmPassword")]
        public string ConfirmPassword { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Surname == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Surname");
            }
            if (Email == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Email");
            }
            if (Password == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Password");
            }
            if (ConfirmPassword == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ConfirmPassword");
            }
            if (this.Name != null)
            {
                if (this.Name.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Name", 1);
                }
            }
            if (this.Surname != null)
            {
                if (this.Surname.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Surname", 1);
                }
            }
            if (this.Email != null)
            {
                if (this.Email.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Email", 1);
                }
            }
            if (this.Password != null)
            {
                if (this.Password.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Password", 1);
                }
            }
            if (this.ConfirmPassword != null)
            {
                if (this.ConfirmPassword.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ConfirmPassword", 1);
                }
            }
        }
    }
}
